### ISSUE TITLE
E-mail

### ISSUE THREAD

**Issue by ghost** [nspo/pybarsys#17]
Hello nspo,

actually i try to set the system on a raspberry pi and i got the problem, i can´t send invoices to users, because i got the Error msg -2.

I tryed to send it via smtp.gmail.com

thy for helping me

**Comment by nspo** [comment]
Have you tried these settings here (both ports):
https://www.lifewire.com/what-are-the-gmail-smtp-settings-1170854 ? If it
does not work, have you tried another mail provider?

Is there anything relevant in the log file /var/log/apache2/error.log?

Am Do., 31. Jan. 2019 um 15:42 Uhr schrieb xandriars <
notifications@github.com>:

**Comment by xandriars** [comment]
If i change all like they do it on the webside the "server" is not longer evailable.

ant this is the Apache2 log:

[Thu Jan 31 15:13:34.045021 2019] [wsgi:error] [pid 3375:tid 1864803376] [remote 192.168.178.161:51954]   File "/var/www/pybarsys/pybarsys/_settings/production_yourbar.py", line 14
[Thu Jan 31 15:13:34.045134 2019] [wsgi:error] [pid 3375:tid 1864803376] [remote 192.168.178.161:51954]     EMAIL_HOST_USER = 'meine_email_adresse'

[Thu Jan 31 15:13:34.045396 2019] [wsgi:error] [pid 3375:tid 1864803376] [remote 192.168.178.161:51954] IndentationError: unexpected indent
[Thu Jan 31 15:13:35.754810 2019] [wsgi:error] [pid 3375:tid 1965466672] [remote 192.168.178.161:51956] mod_wsgi (pid=3375): Target WSGI script '/var/www/pybarsys/pybarsys/wsgi.py' cannot be loaded as Python mod$
[Thu Jan 31 15:13:35.755108 2019] [wsgi:error] [pid 3375:tid 1965466672] [remote 192.168.178.161:51956] mod_wsgi (pid=3375): Exception occurred processing WSGI script '/var/www/pybarsys/pybarsys/wsgi.py'.
[Thu Jan 31 15:13:35.757080 2019] [wsgi:error] [pid 3375:tid 1965466672] [remote 192.168.178.161:51956] Traceback (most recent call last):
[Thu Jan 31 15:13:35.757723 2019] [wsgi:error] [pid 3375:tid 1965466672] [remote 192.168.178.161:51956]   File "/var/www/pybarsys/pybarsys/wsgi.py", line 16, in <module>
[Thu Jan 31 15:13:35.757769 2019] [wsgi:error] [pid 3375:tid 1965466672] [remote 192.168.178.161:51956]     application = get_wsgi_application()
[Thu Jan 31 15:13:35.757861 2019] [wsgi:error] [pid 3375:tid 1965466672] [remote 192.168.178.161:51956]   File "/var/www/pybarsys/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Thu Jan 31 15:13:35.757903 2019] [wsgi:error] [pid 3375:tid 1965466672] [remote 192.168.178.161:51956]     django.setup(set_prefix=False)
[Thu Jan 31 15:13:35.757990 2019] [wsgi:error] [pid 3375:tid 1965466672] [remote 192.168.178.161:51956]   File "/var/www/pybarsys/lib/python3.5/site-packages/django/__init__.py", line 19, in setup

**Comment by nspo** [comment]
You might have put an indentation where there should not be one. See
https://www.python-course.eu/python3_blocks.php

**Comment by xandriars** [comment]
is it possible to contact you on another way?
