### ISSUE TITLE
Create Docker image to simplify installation

### ISSUE THREAD

**Issue by nspo** [nspo/pybarsys#27]

**Comment by Merlijnv** [comment]
@nspo you want some help on this? I have a lot of experience with docker.

**Comment by nspo** [comment]
Always open to suggestions! I think the largest issue is not directly creating the `Dockerfile`/`docker-compose.yml`/etc. but refactoring the `pybarsys` settings so that they are easier to manage without directly messing with Python code. I think [django-environ](https://github.com/joke2k/django-environ) looks like a good candidate. Or do you know something better even?

With `django-environ` we could simply have one basic `settings.py` and load all custom params from `.env` files. And instead of `dev.py`, `production.py` etc. we could provide `.env` file templates.

**Comment by nspo** [comment]
@Merlijnv So I think I have a pretty decent state right now. Do you want to test it? 

The main README is not updated yet but this file explains the new settings strategy:
https://github.com/nspo/pybarsys/blob/feature/docker/docs/settings.md

# Without docker ("traditional" method) but using the new `.env` setup
So, after cloning pybarsys something like the following should do the trick:
```bash
# git clone ...
cd pybarsys
git switch feature/docker
virtualenv -p python3 .
source bin/activate
pip3 install -r requirements.txt
cp .env.example .env # use example settings
scripts/run_test_server.sh
```

This should create a db, migrate it, add a default user (`admin@example.com`, Password `example`) start a test server on http://localhost:8000. You should be able to use the default user to login at http://localhost:8000/admin/

# With docker
```bash
# git clone ... or git clean -xfd if you are working in the same folder and want to clean up
cd pybarsys
cp .env.example .env # use example settings
touch db.sqlite3 # create empty file where DB should be so it can be mounted into container
sudo docker-compose up --build
```

After letting it build and fully start up, you should be able to access pybarsys at http://localhost/ (it uses `nginx` and port 80). The default admin account should also work.

**Comment by Merlijnv** [comment]
@nspo looks and works great u also had the same ideas as me on how to do it. The only thing that I am missing is a minimalist setup by only using a .env file, docker-compose file and automatically build images. that way people don't have to download the whole repo and only those files and the image. But besides that looks promising.

**Comment by nspo** [comment]
You bring up a good point. I tried a few things out on `feature/docker`:
- I split `docker-compose.yml` into two files - one that just references the image and another `docker-compose.build.yml` that can be used as an override to build locally. If people just do `docker-compose up` it will use the image by default.
- It was possible to specify multiple versions in the same `docker-compose.yml` with profiles but I felt like that made it less understandable, thus two files
- Travis CI now also does CD - on each commit, it will automatically build it and tag it (e.g. `feature-docker` for branch `feature/docker`, but `latest` if it's `master`)

It should now be possible to get pybarsys running by doing downloading the [`docker-compose.yml`](https://github.com/nspo/pybarsys/blob/feature/docker/docker-compose.yml) and then
```bash
cp .env.example .env # use example settings
touch db.sqlite3 # create empty file where DB should be so it can be mounted into container
sudo docker-compose up
```

**Comment by Merlijnv** [comment]
Sounds and looks great. Good work. Do you want to me to do anything?

**Comment by nspo** [comment]
I just noticed that there's an issue still - the nginx config is also needed :eyes: I suppose people will just have to download that, too, right? Maybe I'll recommend to download the whole repo and add a script like `setup_pybarsys_in_folder.sh` that just copies the necessary files to a folder?

Would be great if you could do a small test run again:
```
mkdir pybarys
cd pybarsys
mkdir nginx && wget https://raw.githubusercontent.com/nspo/pybarsys/feature/docker/nginx/pybarsys.conf -O nginx/pybarsys.conf
wget https://raw.githubusercontent.com/nspo/pybarsys/feature/docker/docker-compose.yml
wget https://raw.githubusercontent.com/nspo/pybarsys/feature/docker/.env.example -O .env
touch db.sqlite3 # create empty db file
sudo docker-compose up
```

**Comment by Merlijnv** [comment]
Yeah sure I'll test tomorrow morning maybe make a oneliner for the download if the test works?

**Comment by Merlijnv** [comment]
oh just read your idea about little script yeah thats great

**Comment by Merlijnv** [comment]
homelab@homelab:~/pybarsys$ sudo docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by Merlijnv** [comment]
had to upgrade my docker-compose to get it to work. so maybe add instuctions on that in troubleshooting.
Besides that everything works amazing it looks like.

**Comment by nspo** [comment]
Thanks, good feedback! I will try to check the version in the install script and maybe update it optionally if needed

**Comment by Merlijnv** [comment]
@nspo I have send some more feedback in discord
